using System.IO;
using System.Linq;
using System.Text;
using Markdig;
using Markdig.Extensions.Tables;
using Markdig.Syntax;
using Markdig.Syntax.Inlines;
using PdfSharp.Pdf.IO;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Recallr.Models.Services;

public class PdfService
{
    /*
     * This Service was entirely generated by Claude, I do not claim ownership of it.
     */
    
    
    
    private static readonly string ColorHeading = Colors.Blue.Darken2;
    private static readonly string ColorText = Colors.Grey.Darken4;
    private static readonly string ColorQuoteBar = Colors.Blue.Medium;
    private static readonly string ColorQuoteBg = Colors.Blue.Lighten5;
    private static readonly string ColorCodeBg = Colors.Grey.Lighten3;
    private static readonly string ColorTableHeaderBg = Colors.Blue.Lighten4;
    private static readonly string ColorRule = Colors.Grey.Lighten1;

    
    public static int GetDocumentPageCount(string path)
    {
        using (PdfSharp.Pdf.PdfDocument document = PdfReader.Open(path, PdfDocumentOpenMode.InformationOnly))
        {
            return document.PageCount;
        }
    }

    public static void ExportMarkdownAsPdf(string markdownText, string outputFilePath)
    {
        var pipeline = new MarkdownPipelineBuilder()
            .UseAdvancedExtensions() // aktiviert Tabellen, Fußnoten, etc.
            .Build();
 
        var document = Markdig.Markdown.Parse(markdownText, pipeline);
 
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(11).FontColor(ColorText));
 
                page.Content().Column(col =>
                {
                    col.Spacing(4);
                    foreach (var block in document)
                        RenderBlock(col, block);
                });
 
                page.Footer().AlignCenter().Text(t =>
                {
                    t.DefaultTextStyle(x => x.FontSize(9).FontColor(Colors.Grey.Medium));
                    t.CurrentPageNumber();
                    t.Span(" / ");
                    t.TotalPages();
                });
            });
        }).GeneratePdf(outputFilePath);

    }
    
        private static void RenderBlock(ColumnDescriptor col, Block block)
    {
        switch (block)
        {
            case HeadingBlock heading:
                RenderHeading(col, heading);
                break;
 
            case ParagraphBlock paragraph:
                RenderParagraphWithEmojiCheck(col, paragraph);
                break;
 
            case QuoteBlock quote:
                RenderQuote(col, quote);
                break;
 
            case ListBlock list:
                RenderList(col, list, 0);
                break;
 
            case CodeBlock code:
                RenderCodeBlock(col, code);
                break;
 
            case Table table:
                RenderTable(col, table);
                break;
 
            case ThematicBreakBlock:
                col.Item().PaddingVertical(6).LineHorizontal(1).LineColor(ColorRule);
                break;
 
            default:
                // Fallback: unbekannte Blocktypen einfach überspringen statt crashen
                break;
        }
    }
 
    private static void RenderHeading(ColumnDescriptor col, HeadingBlock heading)
    {
        var text = GetPlainText(heading.Inline);
 
        switch (heading.Level)
        {
            case 1:
                col.Item().PaddingTop(10).PaddingBottom(4)
                    .BorderBottom(1).BorderColor(ColorHeading)
                    .Text(text).FontSize(22).Bold().FontColor(ColorHeading);
                break;
            case 2:
                col.Item().PaddingTop(10).PaddingBottom(2)
                    .Text(text).FontSize(17).Bold().FontColor(ColorHeading);
                break;
            case 3:
                col.Item().PaddingTop(8)
                    .Text(text).FontSize(14).Bold().FontColor(ColorText);
                break;
            default:
                col.Item().PaddingTop(6)
                    .Text(text).FontSize(12).Bold().FontColor(ColorText);
                break;
        }
    }
 
    private static void RenderParagraphWithEmojiCheck(ColumnDescriptor col, ParagraphBlock paragraph)
    {
        var plain = GetPlainText(paragraph.Inline);
 
        if (plain.StartsWith("💡") || plain.StartsWith("⚠️"))
        {
            var bg = plain.StartsWith("⚠️") ? Colors.Orange.Lighten4 : Colors.Yellow.Lighten4;
            col.Item().Background(bg).Padding(8).Text(t => RenderInlines(t, paragraph.Inline));
            return;
        }
 
        col.Item().Text(t =>
        {
            t.Justify();
            RenderInlines(t, paragraph.Inline);
        });
    }
 
    private static void RenderQuote(ColumnDescriptor col, QuoteBlock quote)
    {
        col.Item()
            .BorderLeft(3).BorderColor(ColorQuoteBar)
            .Background(ColorQuoteBg)
            .Padding(8)
            .Column(inner =>
            {
                inner.Spacing(4);
                foreach (var sub in quote)
                {
                    if (sub is ParagraphBlock p)
                        inner.Item().Text(t =>
                        {
                            t.DefaultTextStyle(x => x.Italic());
                            RenderInlines(t, p.Inline);
                        });
                    else
                        RenderBlock(inner, sub);
                }
            });
    }
 
    private static void RenderList(ColumnDescriptor col, ListBlock list, int depth)
    {
        var index = 1;
        foreach (var item in list)
        {
            if (item is not ListItemBlock listItem) continue;
 
            foreach (var sub in listItem)
            {
                if (sub is ParagraphBlock p)
                {
                    var bullet = list.IsOrdered ? $"{index}." : "•";
                    col.Item().PaddingLeft(12 + depth * 16).Row(row =>
                    {
                        row.ConstantItem(18).Text(bullet).FontColor(ColorHeading).Bold();
                        row.RelativeItem().Text(t => RenderInlines(t, p.Inline));
                    });
                }
                else if (sub is ListBlock nested)
                {
                    RenderList(col, nested, depth + 1);
                }
                else
                {
                    RenderBlock(col, sub);
                }
            }
            index++;
        }
    }
 
    private static void RenderCodeBlock(ColumnDescriptor col, CodeBlock code)
    {
        var text = code is FencedCodeBlock fenced
            ? string.Join("\n", fenced.Lines.Lines.Select(l => l.ToString()))
            : string.Join("\n", code.Lines.Lines.Select(l => l.ToString()));
 
        col.Item()
            .Background(ColorCodeBg)
            .Padding(8)
            .Text(text)
            .FontFamily("Courier New")
            .FontSize(10);
    }
 
    private static void RenderTable(ColumnDescriptor col, Table table)
    {
        col.Item().PaddingVertical(4).Table(t =>
        {
            var columnCount = table.ColumnDefinitions.Count;
            t.ColumnsDefinition(columns =>
            {
                for (var i = 0; i < columnCount; i++)
                    columns.RelativeColumn();
            });
 
            var isFirstRow = true;
            foreach (TableRow row in table)
            {
                foreach (TableCell cell in row)
                {
                    var cellText = string.Join(" ", cell.OfType<ParagraphBlock>()
                        .Select(p => GetPlainText(p.Inline)));
 
                    var container = t.Cell()
                        .Border(1).BorderColor(Colors.Grey.Lighten2)
                        .Background(isFirstRow || row.IsHeader ? ColorTableHeaderBg : Colors.White)
                        .Padding(6);
 
                    if (row.IsHeader)
                        container.Text(cellText).Bold().FontColor(ColorHeading);
                    else
                        container.Text(cellText);
                }
                isFirstRow = false;
            }
        });
    }
 
    private static void RenderInlines(TextDescriptor t, ContainerInline? inline, bool bold = false, bool italic = false)
    {
        if (inline == null) return;
 
        foreach (var item in inline)
        {
            switch (item)
            {
                case LiteralInline lit:
                    var span = t.Span(lit.Content.ToString());
                    if (bold) span.Bold();
                    if (italic) span.Italic();
                    break;
 
                case EmphasisInline emph:
                    var isBold = emph.DelimiterCount == 2;
                    RenderInlines(t, emph, bold || isBold, italic || !isBold);
                    break;
 
                case CodeInline code:
                    t.Span(code.Content).FontFamily("Courier New").BackgroundColor(ColorCodeBg);
                    break;
 
                case LineBreakInline:
                    t.Span("\n");
                    break;
 
                case LinkInline link:
                    RenderInlines(t, link, bold, italic);
                    break;
 
                default:
                    if (item is ContainerInline container)
                        RenderInlines(t, container, bold, italic);
                    break;
            }
        }
    }
 
    private static string GetPlainText(ContainerInline? inline)
    {
        if (inline == null) return "";
        var sb = new StringBuilder();
        foreach (var item in inline)
        {
            switch (item)
            {
                case LiteralInline lit:
                    sb.Append(lit.Content.ToString());
                    break;
                case ContainerInline container:
                    sb.Append(GetPlainText(container));
                    break;
                case CodeInline code:
                    sb.Append(code.Content);
                    break;
            }
        }
        return sb.ToString();
    }

}